### ISSUE TITLE
pr issure

### ISSUE THREAD

**Issue by LiZhiFeng1111111** [yifeianyi/proj241-PA_for_LA#3]
师兄，由于昨天晚上为了解决diffitest，所以你把remote的github的地址改为了你的，得以拉下最新的代码。今天早上我想将写好的代码push，但是执行了git push github main 的时候出现没有权限上传的问题，于是我把remote的地址更新为我fork后的分支的地址，然后提能push上去。push上去之后在我fork的分支看到的如下信息，因为你早上说提pr不是按这个pull request，但是在头顶没有看到你说的蓝色按钮，以上是我提pr出现的疑惑。
![49516ec5338f2e10573daa5c5c32168](https://github.com/yifeianyi/proj241-PA_for_LA/assets/132964016/4431a740-353c-43a1-a57b-56272be5dd2f)

**Comment by yifeianyi** [comment]
pt提交那是我记错了，你自己看着提示信息交就好（如黄框那样）。
至于你自己上传和同步主分支的问题，可以绑定两个远程仓库地址，一个用来上传你自己的代码，一个用来同步主分支变化

**Comment by LiZhiFeng1111111** [comment]
ok
